### ISSUE TITLE
Request: show how to have horizontal scrolling for the video

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [linlukes/VideoLiveWallpaper#3]
Unless the video resolution is exactly the same as the screen resolution, it gets cropped.
Please show how to have horizontal scrolling.
Maybe will need to use ExoPlayer.

Also, could be nice to see how to perform these operations:
1. Use OpenGL instead.
2. Put an image instead, or as a background to the video.

**Comment by AndroidDeveloperLB** [comment]
@linlukes Why is it closed?
The app now stretches the video.
This means that if I choose a video that is horizontal and the orientation is vertical (or the opposite), it gets distorted...

Not to mention I still get to see crashes when choosing a video file, such as this one:

```
Caused by: java.lang.NullPointerException
	at com.star.videolivewallpaper.activity.MainActivity.onActivityResult(Unknown Source:23)
	at android.app.Activity.internalDispatchActivityResult(Activity.java:9340)
	at android.app.Activity.dispatchActivityResult(Activity.java:9324)
```

This means it often fails to even let me choose a video file. See attached, when I try to open WEBM file:

[files.zip](https://github.com/user-attachments/files/17349101/files.zip)
